easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Alert
        - App\Entity\Contact
        - App\Entity\Article
        - App\Entity\Source
        - App\Entity\Image
        - App\Entity\User
