easy_admin:
    site_name: 'Covid19 Administration'
    design:
        brand_color: '#14da94'
    entities:
        - App\Entity\Cases
        - App\Entity\Alert
        - App\Entity\Contact
        - App\Entity\Article
        - App\Entity\Source
        - App\Entity\Image
